[package]
name = "puppylog"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = { version = "0.8", features = ["macros"] }
serde = { version = "1", features = ["derive"] }
chrono = "0.4"
tower-http = { version = "0.6", features = ["decompression-gzip"] }
futures-util = "0.3"